[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.17"

# TODO: Update branch once merged
[[constraint]]
  branch = "version-update"
  name = "github.com/republicprotocol/republic-go"

# TODO: Update branch once merged
[[constraint]]
  branch = "config"
  name = "github.com/republicprotocol/renex-ingress-go"

# Fix to resolve dependency issues within go-ethereum
[[override]]
  name = "gopkg.in/fatih/set.v0"
  version = "=0.1.0"

[prune]
  go-tests = true